baseURL = "https://cocolu9309-cloud.github.io/marketing-intelligency/"
locale = "zh-CN"
title = "callie.com 营销资讯中心"
theme = []

[outputs]
home = ["HTML"]

[taxonomies]
department = "department"
content_type = "content_type"

[params]
description = "全球前沿营销玩法资讯，实时更新"